apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: platform-service
  name: platform-service
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service
  template:
    metadata:
      labels:
        app: platform-service
    spec:
      containers:
      - image: navaneethknharness/rodemo-platform-service:1.0.14
        name: platform-service
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
