apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-gateway
  name: payment-gateway
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
      - image: navaneethknharness/rodemo-payment-gateway:1.0.24
        name: payment-gateway
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
