apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: rodemo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: rodemo
  namespace: rodemo
spec:
  promotionPolicies:
  - stageSelector:
      name: "glob:*"
    autoPromotionEnabled: false
