apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-system
  namespace: rodemo
spec:
  vars:
  - name: gitopsRepo
  - name: envName
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitopsRepo }}
      checkout:
      - branch: main
        path: ./src
      - branch: stage/${{ vars.envName }}
        create: true
        path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: kustomize-set-image
    as: update-payment-gateway
    config:
      path: ./src/apps/payment-gateway/base
      images:
      - image: navaneethknharness/rodemo-payment-gateway
        tag: ${{ imageFrom("navaneethknharness/rodemo-payment-gateway").Tag }}
  - uses: kustomize-set-image
    as: update-platform-service
    config:
      path: ./src/apps/platform-service/base
      images:
      - image: navaneethknharness/rodemo-platform-service
        tag: ${{ imageFrom("navaneethknharness/rodemo-platform-service").Tag }}
  - uses: kustomize-build
    config:
      path: ./src/apps/payment-gateway/stages/${{ vars.envName }}
      outPath: ./out
  - uses: kustomize-build
    config:
      path: ./src/apps/platform-service/stages/${{ vars.envName }}
      outPath: ./out
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: |
        ${{ task.outputs['update-payment-gateway'].commitMessage }}
        ${{ task.outputs['update-platform-service'].commitMessage }}
  - uses: git-push
    config:
      path: ./out
  - uses: argocd-update
    config:
      apps:
      - name: ${{ ctx.stage }}
        sources:
        - repoURL: ${{ vars.gitopsRepo }}
          desiredRevision: ${{ task.outputs.commit.commit }}
