apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-app
  namespace: rodemo
spec:
  vars:
  - name: gitopsRepo
  - name: imageRepo
  - name: appName
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitopsRepo }}
      checkout:
      - branch: main
        path: ./repo
  - uses: kustomize-set-image
    as: update
    config:
      path: ./repo/apps/${{ vars.appName }}/stages/${{ ctx.stage }}
      images:
      - image: ${{ vars.imageRepo }}
        tag: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: git-commit
    as: commit
    config:
      path: ./repo
      message: ${{ task.outputs.update.commitMessage }}
  - uses: git-push
    config:
      path: ./repo
  - uses: argocd-update
    config:
      apps:
      - name: ${{ vars.appName }}-${{ ctx.stage }}
        sources:
        - repoURL: ${{ vars.gitopsRepo }}
          desiredRevision: ${{ task.outputs.commit.commit }}
