apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: rodemo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: system-release
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitopsRepo
        value: https://github.com/navaneeth/kargo-test.git
      - name: envName
        value: dev
      steps:
      - task:
          name: promote-system
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: qa
  namespace: rodemo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: system-release
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars:
      - name: gitopsRepo
        value: https://github.com/navaneeth/kargo-test.git
      - name: envName
        value: qa
      steps:
      - task:
          name: promote-system
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: rodemo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: system-release
    sources:
      stages:
      - qa
  promotionTemplate:
    spec:
      vars:
      - name: gitopsRepo
        value: https://github.com/navaneeth/kargo-test.git
      - name: envName
        value: prod
      steps:
      - task:
          name: promote-system-reviewed
        as: promo-process
