apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: system-release
  namespace: rodemo
spec:
  subscriptions:
  - image:
      repoURL: navaneethknharness/rodemo-payment-gateway
      constraint: ^1.0.0
      discoveryLimit: 10
  - image:
      repoURL: navaneethknharness/rodemo-platform-service
      constraint: ^1.0.0
      discoveryLimit: 10
