apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-service
  labels:
    app: platform-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service
  template:
    metadata:
      labels:
        app: platform-service
    spec:
      containers:
      - name: platform-service
        image: navaneethknharness/rodemo-platform-service:placeholder
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
