apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rodemo
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - stage: dev
      - stage: qa
      - stage: prod
  template:
    metadata:
      name: '{{.stage}}'
      annotations:
        kargo.akuity.io/authorized-stage: 'rodemo:{{.stage}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/navaneeth/kargo-test.git
        targetRevision: 'stage/{{.stage}}'
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.stage}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
